import mongoose from "mongoose";

const paymentSchema = new mongoose.Schema(
  {
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      required: true,
      index: true,
    },

    enrollmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Enrollment",
      required: true,
    },

    amount: {
      type: Number,
      required: true,
    },

    currency: {
      type: String,
      default: "INR",
    },

    razorpayOrderId: String,
    razorpayPaymentId: String,
    razorpaySignature: String,

    status: {
      type: String,
      enum: ["pending", "paid", "failed"],
      default: "pending",
      index: true,
    },

    invoiceNumber: String,
    paidAt: Date,

    // ── Monthly billing fields ─────────────────────────────────────────────────
    type: {
      type: String,
      enum: ["initial", "monthly"],
      default: "initial",
    },
    billingMonth: {
      type: String,   // "YYYY-MM" e.g. "2026-03"
      default: "",
    },
    dueDate: {
      type: Date,     // payment must be completed by this date
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

export default mongoose.model("Payment", paymentSchema);