import cron from "node-cron";
import Enrollment from "../models/Enrollment.model.js";
import Payment from "../models/Payment.model.js";
import { addOneMonth, billingMonthStr } from "./helpers.js";

// ── Job 1: Generate monthly invoices ─────────────────────────────────────────
// Runs every day at 00:05 AM IST
// Finds all active enrollments whose nextBillingDate is today or past,
// creates a pending Payment record, and advances nextBillingDate by 1 month.
async function generateMonthlyInvoices() {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const due = await Enrollment.find({
      status: "active",
      nextBillingDate: { $lte: today },
    }).lean();

    if (due.length === 0) return;

    // Batch check for existing payments to avoid N queries
    const dueBillingKeys = due.map((e) => ({
      enrollmentId: e._id,
      billingMonth: billingMonthStr(e.nextBillingDate),
    }));

    const existingPayments = await Payment.find({
      $or: dueBillingKeys.map((k) => ({
        enrollmentId: k.enrollmentId,
        billingMonth: k.billingMonth,
        type: "monthly",
      })),
    })
      .select("enrollmentId billingMonth")
      .lean();

    const existingSet = new Set(
      existingPayments.map((p) => `${p.enrollmentId}-${p.billingMonth}`)
    );

    const paymentsToCreate = [];
    const bulkEnrollmentOps = [];

    for (const enrollment of due) {
      const billingMonth = billingMonthStr(enrollment.nextBillingDate);
      const key = `${enrollment._id}-${billingMonth}`;

      if (!existingSet.has(key)) {
        const dueDate = new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000);
        paymentsToCreate.push({
          studentId: enrollment.studentId,
          enrollmentId: enrollment._id,
          amount: enrollment.price,
          type: "monthly",
          billingMonth,
          dueDate,
          isAutoGenerated: true,
          status: "pending",
          razorpayOrderId: "",
          currency: "INR",
        });
      }

      // Advance nextBillingDate regardless
      bulkEnrollmentOps.push({
        updateOne: {
          filter: { _id: enrollment._id },
          update: {
            $set: {
              nextBillingDate: addOneMonth(enrollment.nextBillingDate),
            },
          },
        },
      });
    }

    // Batch insert payments + batch update enrollments
    if (paymentsToCreate.length > 0) {
      await Payment.insertMany(paymentsToCreate);
      console.log(
        `[Scheduler] Monthly invoices generated: ${paymentsToCreate.length}`
      );
    }

    if (bulkEnrollmentOps.length > 0) {
      await Enrollment.bulkWrite(bulkEnrollmentOps);
    }
  } catch (err) {
    console.error("[Scheduler] generateMonthlyInvoices error:", err.message);
  }
}

// ── Job 2: Mark overdue enrollments ──────────────────────────────────────────
// Runs every day at 00:10 AM IST
async function markOverdueEnrollments() {
  try {
    const now = new Date();

    const overduePayments = await Payment.find({
      status: "pending",
      dueDate: { $lt: now },
    }).distinct("enrollmentId");

    if (overduePayments.length === 0) return;

    const result = await Enrollment.updateMany(
      { _id: { $in: overduePayments }, status: "active" },
      { $set: { status: "overdue" } }
    );

    if (result.modifiedCount > 0) {
      console.log(
        `[Scheduler] Enrollments marked overdue: ${result.modifiedCount}`
      );
    }
  } catch (err) {
    console.error("[Scheduler] markOverdueEnrollments error:", err.message);
  }
}

// ── Start all cron jobs ───────────────────────────────────────────────────────
export function startScheduler() {
  cron.schedule("5 0 * * *", generateMonthlyInvoices, {
    timezone: "Asia/Kolkata",
  });
  cron.schedule("10 0 * * *", markOverdueEnrollments, {
    timezone: "Asia/Kolkata",
  });

  console.log("[Scheduler] Billing scheduler started (IST timezone)");
}
