import cron from "node-cron";
import Enrollment from "../models/Enrollment.model.js";
import Payment from "../models/Payment.model.js";

// ── Helper: add 1 month to a Date ────────────────────────────────────────────
function addOneMonth(date) {
  const d = new Date(date);
  d.setMonth(d.getMonth() + 1);
  return d;
}

function billingMonthStr(date) {
  const d = new Date(date);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

// ── Job 1: Generate monthly invoices ─────────────────────────────────────────
// Runs every day at 00:05 AM
// Finds all active enrollments whose nextBillingDate is today or past,
// creates a pending Payment record, and advances nextBillingDate by 1 month.
async function generateMonthlyInvoices() {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Active enrollments where next billing date has arrived
    const due = await Enrollment.find({
      status: "active",
      nextBillingDate: { $lte: today },
    });

    let created = 0;
    for (const enrollment of due) {
      const billingMonth = billingMonthStr(enrollment.nextBillingDate);

      // Avoid duplicate: skip if a payment already exists for this month
      const exists = await Payment.findOne({
        enrollmentId: enrollment._id,
        billingMonth,
        type: "monthly",
      });

      if (!exists) {
        const dueDate = new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000); // due in 5 days
        await Payment.create({
          studentId: enrollment.studentId,
          enrollmentId: enrollment._id,
          amount: enrollment.price,
          type: "monthly",
          billingMonth,
          dueDate,
          isAutoGenerated: true,
          status: "pending",
          razorpayOrderId: "",
          currency: "INR",
        });
        created++;
      }

      // Advance nextBillingDate by 1 month regardless
      enrollment.nextBillingDate = addOneMonth(enrollment.nextBillingDate);
      await enrollment.save();
    }

    if (created > 0) {
      console.log(`[Scheduler] Monthly invoices generated: ${created}`);
    }
  } catch (err) {
    console.error("[Scheduler] generateMonthlyInvoices error:", err.message);
  }
}

// ── Job 2: Mark overdue enrollments ──────────────────────────────────────────
// Runs every day at 00:10 AM
// Finds pending payments past their dueDate and marks the enrollment as overdue.
async function markOverdueEnrollments() {
  try {
    const now = new Date();

    const overduePayments = await Payment.find({
      status: "pending",
      dueDate: { $lt: now },
    }).distinct("enrollmentId");

    if (overduePayments.length === 0) return;

    const result = await Enrollment.updateMany(
      { _id: { $in: overduePayments }, status: "active" },
      { $set: { status: "overdue" } }
    );

    if (result.modifiedCount > 0) {
      console.log(`[Scheduler] Enrollments marked overdue: ${result.modifiedCount}`);
    }
  } catch (err) {
    console.error("[Scheduler] markOverdueEnrollments error:", err.message);
  }
}

// ── Start all cron jobs ───────────────────────────────────────────────────────
export function startScheduler() {
  // Generate monthly invoices — daily at 00:05 AM
  cron.schedule("5 0 * * *", generateMonthlyInvoices, { timezone: "Asia/Kolkata" });

  // Mark overdue enrollments — daily at 00:10 AM
  cron.schedule("10 0 * * *", markOverdueEnrollments, { timezone: "Asia/Kolkata" });

  console.log("[Scheduler] Billing scheduler started (IST timezone)");
}
